import {
  Waves,
  Flame,
  ShieldCheck,
  Wifi,
  Snowflake,
  Ship,
  Trees,
  Bath,
  Droplets,
  Beef,
  Car,
  PawPrint,
  Baby,
  Utensils,
  WashingMachine,
  CookingPot,
  Tv,
  Dumbbell,
  Gamepad2,
  Zap,
  Fence,
  type LucideIcon,
} from "lucide-react";
import type { AmenityKey } from "./types";

export const amenityIcons: Record<AmenityKey, LucideIcon> = {
  privatePool: Waves,
  heatedPool: Flame,
  protectedPool: ShieldCheck,
  wifi: Wifi,
  airCon: Snowflake,
  seaView: Ship,
  natureView: Trees,
  jacuzzi: Bath,
  sauna: Droplets,
  bbq: Beef,
  parking: Car,
  petFriendly: PawPrint,
  babyCot: Baby,
  dishwasher: Utensils,
  washingMachine: WashingMachine,
  kitchen: CookingPot,
  tv: Tv,
  fireplace: Flame,
  gym: Dumbbell,
  gameRoom: Gamepad2,
  kidsPool: Waves,
  childproof: Fence,
  generator: Zap,
};
