// Bu dosya artık uygulamada kullanılmıyor — yalnızca ilk aktarımın kaynağı.
// Gerçek veri Supabase'de; değişiklikler oradan yapılır.
import type { Villa } from "../../src/lib/types.ts";

/** Placeholder gallery images — swap these for real villa photos later. */
const img = (seed: string, n: number, w = 1200, h = 800) =>
  `https://picsum.photos/seed/${seed}-${n}/${w}/${h}`;

const gallery = (seed: string, count = 6) =>
  Array.from({ length: count }, (_, i) => img(seed, i + 1));

export const regions = [
  { slug: "kalkan", name: "Kalkan", province: "Antalya" },
  { slug: "kas", name: "Kaş", province: "Antalya" },
  { slug: "fethiye", name: "Fethiye", province: "Muğla" },
  { slug: "kalkan-islamlar", name: "İslamlar", province: "Antalya" },
  { slug: "bodrum", name: "Bodrum", province: "Muğla" },
  { slug: "gocek", name: "Göcek", province: "Muğla" },
];

export const villas: Villa[] = [
  {
    slug: "villa-deniz-kalkan",
    name: "Villa Deniz",
    region: "Kalkan",
    province: "Antalya",
    images: gallery("villadeniz"),
    videoUrl: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    capacity: 8,
    bedrooms: 4,
    bathrooms: 3,
    pool: "private",
    size: 240,
    distanceToSea: 400,
    rating: 4.9,
    reviewCount: 128,
    featured: true,
    amenities: [
      "privatePool",
      "seaView",
      "wifi",
      "airCon",
      "jacuzzi",
      "bbq",
      "parking",
      "childproof",
      "kitchen",
      "washingMachine",
      "tv",
    ],
    descriptionTr:
      "Kalkan'ın eşsiz deniz manzarasına hâkim, korunaklı özel havuzlu lüks villa. Geniş terasında akşam yemekleri, jakuzide gün batımı keyfi sizi bekliyor. Aileler ve kalabalık gruplar için ideal.",
    descriptionEn:
      "A luxury villa with a protected private pool overlooking Kalkan's unique sea view. Enjoy dinners on the spacious terrace and sunsets in the jacuzzi. Ideal for families and larger groups.",
    checkIn: "16:00",
    checkOut: "10:00",
    minNights: 3,
    pricePerNight: 12500,
    bookedRanges: [
      { start: "2026-07-25", end: "2026-08-02" },
      { start: "2026-08-14", end: "2026-08-21" },
    ],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 8500 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 11000 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 12500 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-09-01", end: "2026-10-15", price: 10000 },
    ],
  },
  {
    slug: "villa-lavanta-islamlar",
    name: "Villa Lavanta",
    region: "İslamlar",
    province: "Antalya",
    images: gallery("villalavanta"),
    capacity: 6,
    bedrooms: 3,
    bathrooms: 2,
    pool: "private",
    size: 180,
    distanceToSea: 6000,
    rating: 4.8,
    reviewCount: 74,
    featured: true,
    discountPercent: 20,
    dealTag: "shortStay",
    amenities: [
      "privatePool",
      "natureView",
      "wifi",
      "airCon",
      "bbq",
      "parking",
      "petFriendly",
      "fireplace",
      "kitchen",
      "dishwasher",
    ],
    descriptionTr:
      "İslamlar'ın serin yaylasında, çam ve zeytin ağaçlarıyla çevrili huzur dolu bir kaçamak. Doğayla iç içe, özel havuzlu, evcil hayvan dostu villa.",
    descriptionEn:
      "A peaceful getaway on the cool İslamlar plateau, surrounded by pine and olive trees. A pet-friendly villa with a private pool, right in the middle of nature.",
    checkIn: "16:00",
    checkOut: "10:00",
    minNights: 2,
    pricePerNight: 7800,
    bookedRanges: [{ start: "2026-07-21", end: "2026-07-28" }],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 5200 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 6800 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 7800 },
    ],
  },
  {
    slug: "villa-mavi-kas",
    name: "Villa Mavi",
    region: "Kaş",
    province: "Antalya",
    images: gallery("villamavi"),
    videoUrl: "https://www.youtube.com/embed/ScMzIvxBSi4",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    pool: "private",
    size: 130,
    distanceToSea: 150,
    rating: 4.7,
    reviewCount: 52,
    featured: true,
    discountPercent: 15,
    dealTag: "lastMinute",
    amenities: [
      "privatePool",
      "seaView",
      "wifi",
      "airCon",
      "jacuzzi",
      "parking",
      "kitchen",
      "tv",
    ],
    descriptionTr:
      "Kaş merkeze yürüme mesafesinde, denize sıfır konumda şık bir bal ayı villası. Çiftler ve küçük aileler için romantik bir seçenek.",
    descriptionEn:
      "A chic honeymoon villa within walking distance of Kaş center, right by the sea. A romantic option for couples and small families.",
    checkIn: "15:00",
    checkOut: "10:00",
    minNights: 3,
    pricePerNight: 9200,
    bookedRanges: [
      { start: "2026-08-01", end: "2026-08-10" },
    ],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 6500 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 8000 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 9200 },
    ],
  },
  {
    slug: "villa-orman-fethiye",
    name: "Villa Orman",
    region: "Fethiye",
    province: "Muğla",
    images: gallery("villaorman"),
    capacity: 10,
    bedrooms: 5,
    bathrooms: 4,
    pool: "private",
    size: 320,
    distanceToSea: 2500,
    rating: 4.9,
    reviewCount: 96,
    featured: true,
    amenities: [
      "privatePool",
      "heatedPool",
      "natureView",
      "wifi",
      "airCon",
      "sauna",
      "gameRoom",
      "bbq",
      "parking",
      "childproof",
      "babyCot",
      "kitchen",
      "washingMachine",
      "dishwasher",
    ],
    descriptionTr:
      "Fethiye'nin yemyeşil doğasında, ısıtmalı havuzu ve oyun odasıyla kalabalık aileler için tasarlanmış geniş bir villa. Korunaklı bahçe çocuklar için güvenli.",
    descriptionEn:
      "A spacious villa in Fethiye's lush nature, designed for large families with a heated pool and game room. The enclosed garden is safe for children.",
    checkIn: "16:00",
    checkOut: "11:00",
    minNights: 4,
    pricePerNight: 15800,
    bookedRanges: [{ start: "2026-07-30", end: "2026-08-15" }],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 11000 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 13500 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 15800 },
    ],
  },
  {
    slug: "villa-inci-bodrum",
    name: "Villa İnci",
    region: "Bodrum",
    province: "Muğla",
    images: gallery("villainci"),
    capacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    pool: "private",
    size: 200,
    distanceToSea: 800,
    rating: 4.6,
    reviewCount: 41,
    featured: false,
    discountPercent: 10,
    dealTag: "earlyBooking",
    amenities: [
      "privatePool",
      "seaView",
      "wifi",
      "airCon",
      "jacuzzi",
      "gym",
      "parking",
      "kitchen",
      "tv",
      "dishwasher",
    ],
    descriptionTr:
      "Bodrum'un gözde koyuna bakan, modern mimarili özel havuzlu villa. Fitness odası ve infinity havuzuyla konforlu bir tatil.",
    descriptionEn:
      "A modern private-pool villa overlooking one of Bodrum's favorite bays. A comfortable holiday with a fitness room and infinity pool.",
    checkIn: "16:00",
    checkOut: "10:00",
    minNights: 3,
    pricePerNight: 10500,
    bookedRanges: [{ start: "2026-08-05", end: "2026-08-12" }],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 7200 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 9000 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 10500 },
    ],
  },
  {
    slug: "villa-zeytin-gocek",
    name: "Villa Zeytin",
    region: "Göcek",
    province: "Muğla",
    images: gallery("villazeytin"),
    capacity: 8,
    bedrooms: 4,
    bathrooms: 3,
    pool: "private",
    size: 260,
    distanceToSea: 1200,
    rating: 4.8,
    reviewCount: 63,
    featured: false,
    discountPercent: 25,
    dealTag: "shortStay",
    amenities: [
      "privatePool",
      "natureView",
      "wifi",
      "airCon",
      "bbq",
      "parking",
      "petFriendly",
      "childproof",
      "kitchen",
      "washingMachine",
      "fireplace",
    ],
    descriptionTr:
      "Göcek'in sakin koylarına yakın, zeytinlikler içinde geniş bahçeli bir villa. Doğa yürüyüşü ve tekne turlarına ideal konum.",
    descriptionEn:
      "A villa with a large garden among olive groves, close to Göcek's calm bays. An ideal base for nature walks and boat tours.",
    checkIn: "16:00",
    checkOut: "10:00",
    minNights: 3,
    pricePerNight: 11200,
    bookedRanges: [],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 7800 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 9600 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 11200 },
    ],
  },
  {
    slug: "villa-gunes-kalkan",
    name: "Villa Güneş",
    region: "Kalkan",
    province: "Antalya",
    images: gallery("villagunes"),
    capacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    pool: "private",
    size: 110,
    distanceToSea: 900,
    rating: 4.5,
    reviewCount: 38,
    featured: false,
    discountPercent: 15,
    dealTag: "lastMinute",
    amenities: [
      "privatePool",
      "seaView",
      "wifi",
      "airCon",
      "parking",
      "kitchen",
      "tv",
    ],
    descriptionTr:
      "Kalkan yamaçlarında, bütçe dostu ama konforlu, korunaklı havuzlu şirin bir villa. Çiftler ve küçük aileler için ideal.",
    descriptionEn:
      "A cozy, budget-friendly yet comfortable villa with a protected pool on the Kalkan hillside. Ideal for couples and small families.",
    checkIn: "16:00",
    checkOut: "10:00",
    minNights: 2,
    pricePerNight: 6400,
    bookedRanges: [{ start: "2026-07-22", end: "2026-07-26" }],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 4200 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 5400 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 6400 },
    ],
  },
  {
    slug: "villa-panorama-kas",
    name: "Villa Panorama",
    region: "Kaş",
    province: "Antalya",
    images: gallery("villapanorama"),
    videoUrl: "https://www.youtube.com/embed/hHW1oY26kxQ",
    capacity: 12,
    bedrooms: 6,
    bathrooms: 5,
    pool: "private",
    size: 400,
    distanceToSea: 500,
    rating: 5.0,
    reviewCount: 87,
    featured: true,
    amenities: [
      "privatePool",
      "heatedPool",
      "seaView",
      "wifi",
      "airCon",
      "jacuzzi",
      "sauna",
      "gym",
      "gameRoom",
      "bbq",
      "parking",
      "generator",
      "childproof",
      "kitchen",
      "washingMachine",
      "dishwasher",
      "tv",
    ],
    descriptionTr:
      "Kaş'ın en üst noktasında, 180° kesintisiz deniz manzaralı ultra lüks villa. İki büyük grup ya da geniş aile için jeneratör, sauna ve spor salonu dahil tam donanım.",
    descriptionEn:
      "An ultra-luxury villa at the highest point of Kaş with an uninterrupted 180° sea view. Fully equipped with a generator, sauna and gym for two large groups or an extended family.",
    checkIn: "16:00",
    checkOut: "11:00",
    minNights: 5,
    pricePerNight: 24000,
    bookedRanges: [{ start: "2026-08-08", end: "2026-08-22" }],
    seasons: [
      { labelTr: "Düşük Sezon", labelEn: "Low Season", start: "2026-04-15", end: "2026-06-01", price: 17000 },
      { labelTr: "Orta Sezon", labelEn: "Mid Season", start: "2026-06-01", end: "2026-07-01", price: 20500 },
      { labelTr: "Yüksek Sezon", labelEn: "High Season", start: "2026-07-01", end: "2026-09-01", price: 24000 },
    ],
  },
];

export function getVilla(slug: string): Villa | undefined {
  return villas.find((v) => v.slug === slug);
}

export function getFeatured(): Villa[] {
  return villas.filter((v) => v.featured);
}

/** Tesis kodu — slug'dan deterministik üretilir (ör. KBV1234). */
export function villaCode(slug: string): string {
  const sum = Array.from(slug).reduce((a, c) => a + c.charCodeAt(0), 0);
  return `KBV${1000 + ((sum * 37) % 9000)}`;
}

/** Sezonluk fiyatlardan gecelik fiyat aralığı (min–max). */
export function priceRange(v: Villa): { min: number; max: number } {
  const prices = v.seasons.map((s) => s.price);
  return { min: Math.min(...prices), max: Math.max(...prices) };
}
